name: Delete XML Files

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete all XML files from data/
        run: |
          git rm data/*.xml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Remove XML files from data folder"
          git push
