name: Delete Lindsell Train Data

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete Lindsell Train files
        run: |
          git rm data/lindsell_train_*
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Remove stale Lindsell Train data for CIK correction"
          git push
